INSERT INTO brands (name, created_by)
VALUES
    ('Tesla', 1),
    ('Microsoft', 1),
    ('Nike', 1),
    ('Apple', 1),
    ('Amazon', 1),
    ('Google', 1),
    ('Samsung', 1),
    ('Coca-Cola', 1),
    ('Toyota', 1),
    ('McDonald\'s', 1),
    ('IBM', 1),
    ('Sony', 1),
    ('BMW', 1),
    ('Adidas', 1),
    ('Honda', 1),
    ('Facebook', 1),
    ('Twitter', 1),
    ('Instagram', 1),
    ('Snapchat', 1),
    ('Netflix', 1),
    ('Pinterest', 1),
    ('LinkedIn', 1),
    ('Uber', 1),
    ('Airbnb', 1),
    ('Spotify', 1),
    ('PayPal', 1),
    ('Visa', 1),
    ('Mastercard', 1),
    ('American Express', 1),
    ('Dell', 1),
    ('Intel', 1),
    ('HP', 1),
    ('Cisco', 1),
    ('Oracle', 1),
    ('Adobe', 1),
    ('Qualcomm', 1),
    ('Verizon', 1),
    ('AT&T', 1),
    ('T-Mobile', 1),
    ('Sprint', 1),
    ('LG', 1),
    ('Panasonic', 1),
    ('Sharp', 1),
    ('Philips', 1),
    ('Nokia', 1),
    ('Vodafone', 1),
    ('Orange', 1),
    ('Tata', 1),
    ('Reliance', 1),
    ('Airtel', 1),
    ('Jio', 1),
    ('Walmart', 1),
    ('Target', 1),
    ('Best Buy', 1),
    ('Home Depot', 1),
    ('Lowe\'s', 1),
    ('Costco', 1),
    ('Walgreens', 1),
    ('CVS', 1),
    ('Starbucks', 1),
    ('Burger King', 1),
    ('Wendy\'s', 1),
    ('KFC', 1),
    ('Subway', 1),
    ('Pizza Hut', 1),
    ('Domino\'s', 1),
    ('Pepsi', 1),
    ('Sprite', 1),
    ('Fanta', 1),
    ('Mountain Dew', 1),
    ('Gatorade', 1),
    ('Red Bull', 1),
    ('Monster', 1),
    ('Under Armour', 1),
    ('Puma', 1),
    ('Reebok', 1),
    ('New Balance', 1),
    ('Converse', 1),
    ('Vans', 1),
    ('Gucci', 1),
    ('Prada', 1),
    ('Louis Vuitton', 1),
    ('Hermes', 1),
    ('Chanel', 1),
    ('Dior', 1),
    ('Versace', 1),
    ('Rolex', 1),
    ('Cartier', 1),
    ('Tiffany & Co.', 1),
    ('Burberry', 1),
    ('Michael Kors', 1),
    ('Lamborghini', 1),
    ('Ferrari', 1),
    ('Porsche', 1),
    ('Audi', 1),
    ('Mercedes-Benz', 1),
    ('Volkswagen', 1),
    ('Ford', 1),
    ('Chevrolet', 1),
    ('Nissan', 1)
